### PR TITLE
Add Galaxy Training Academy to the landing page

### PR DESCRIPTION
**Pull request by bedroesb**
image

### CODE REVIEW

**Comment by pauldg** [comment]
Thanks Bert

**Comment by B0r1sD** [comment]
Event is over, can this branch simply be reverted? 😅

**Comment by bedroesb** [comment]
Currently we always just commented out the event, so it can be used as inspiration, since it has always been different. Maybe we either decide to do a full cleanup. or we also comment out this?

**Comment by B0r1sD** [comment]
As it looks like the styling is still a bit different to tiles that are already commented out, it's indeed nice to have a reference for future tiles.

**Pull request merged**
